# Generated by Django 3.2.6 on 2021-08-30 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_id', models.CharField(max_length=255, unique=True)),
                ('reuse_count', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('mass_delivered', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rockets.core')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='favouritecore',
            constraint=models.UniqueConstraint(fields=('core', 'user'), name='unique core for user'),
        ),
    ]
